name: Job Recruiter Bot
on:
  push:
jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set secrets
        env:
          LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: echo "Secrets are ready"
      - name: Run app
        run: python main.py